# Generated by Django 4.2.4 on 2026-03-30 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('storage_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_location', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_type', models.CharField(choices=[('Normal', 'Normal'), ('Fast', 'Fast')], max_length=20)),
                ('order_status', models.CharField(choices=[('Placed', 'Placed'), ('Picking', 'Picking'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Delayed', 'Delayed')], default='Placed', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.product')),
            ],
        ),
    ]
