# Generated by Django 4.2.4 on 2026-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/200'),
        ),
    ]
