# Generated by Django 4.2.4 on 2026-04-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_warehouse_order_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='assigned_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
