# Generated by Django 4.2.4 on 2026-05-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0006_deliverypartner_assigned_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.seller'),
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(default='seller@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(default='My Shop', max_length=100),
        ),
    ]
