# Generated by Django 4.2.4 on 2026-05-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_product_seller_seller_email_seller_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingapp.deliverypartner'),
        ),
        migrations.AddField(
            model_name='order',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Picking', 'Picking'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Delayed', 'Delayed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
