# Generated by Django 4.2.4 on 2026-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0008_order_delivery_partner_order_reward_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Picking', 'Picking'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
