# Generated by Django 4.2.4 on 2026-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0012_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.CharField(default='3 Days', max_length=100),
        ),
    ]
