# Generated by Django 4.2.4 on 2026-05-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0014_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_id',
            field=models.CharField(default='PKG000', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='packing_counter',
            field=models.CharField(default='Counter 1', max_length=100),
        ),
    ]
