# Generated by Django 4.2.4 on 2026-05-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0015_order_package_id_order_packing_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(default='Low', max_length=50),
        ),
    ]
