# Generated by Django 4.2.4 on 2026-05-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0016_order_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
