# Generated by Django 4.2.4 on 2026-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0017_remove_review_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('worker_role', models.CharField(default='Packing Staff', max_length=100)),
                ('assigned_counter', models.CharField(max_length=100)),
            ],
        ),
    ]
