# Generated by Django 4.2.4 on 2026-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0018_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
