# Generated by Django 4.2.4 on 2026-05-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0019_seller_business_email_seller_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
    ]
