# Generated by Django 4.2.4 on 2026-05-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0020_deliverypartner_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
