# Generated by Django 4.2.4 on 2026-05-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0021_customer_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='South India', max_length=100),
        ),
    ]
